/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import AirplaneManagement.BAirplaneManagement;
import AirplaneManagement.IAirplaneManagement;
import AplicationObject.IAirplane;
import AplicationObject.IAirport;
import AplicationObject.IFlight;
import DataAccess.BDataManagement;
import DataAccess.IDataManagement;
import DataAccess.IObserver;
import GettingAirportAccess.BAirportAccess;
import GettingAirportAccess.IAirportAccess;
import ManagementFlightsAtCompany.BManagementFlights;
import ManagementFlightsAtCompany.IManagementFlights;
import java.util.Iterator;
import javax.swing.JPanel;
import logon.BAuthentication;
import logon.IRole;

/**
 *
 * @author Evgeniy
 */
public class ViewCreateFligths extends JPanel implements IView, IObserver{

    IDataManagement dm_local;
    IRole r = BAuthentication.getRole();
    IRole manegerRole = BAuthentication.getRole("manager", "123");
    /**
     * Creates new form ViewCreateFligths
     */
    public ViewCreateFligths() {
        initComponents();
        dm_local = BDataManagement.build();
        ComboBoxFrom.removeAllItems();
        ComboBoxTo.removeAllItems();
        ComboBoxAirplane.removeAllItems();
        ComboBoxFrom.revalidate();
        ComboBoxTo.revalidate();
        ComboBoxAirplane.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxFrom = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxTo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxAirplane = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        departureTime = new com.toedter.calendar.JDateChooser();
        arrivalTime = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        ButtonSchedule = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ComboBoxFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFromActionPerformed(evt);
            }
        });

        jLabel1.setText("Из:");

        jLabel2.setText("В:");

        ComboBoxTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Самолет:");

        ComboBoxAirplane.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Отлет:");

        departureTime.setDateFormatString("MMM d, yyyy HH:MM");

        arrivalTime.setDateFormatString("MMM d, yyyy HH:MM");

        jLabel5.setText("Прилет:");

        ButtonSchedule.setText("запланировать рейс");
        ButtonSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxAirplane, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departureTime, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(arrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonScheduleActionPerformed
        IManagementFlights mfl = BManagementFlights.build(manegerRole);
        
        IAirport airport1 = (IAirport)ComboBoxFrom.getSelectedItem();
        IAirport airport2 = (IAirport)ComboBoxTo.getSelectedItem();
        IAirplane ap = (IAirplane)ComboBoxAirplane.getSelectedItem();
        
        IFlight fl1 = mfl.addFlight(airport1, airport2, ap, 
                departureTime.getDate(), arrivalTime.getDate());
    }//GEN-LAST:event_ButtonScheduleActionPerformed

    private void ComboBoxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSchedule;
    private javax.swing.JComboBox ComboBoxAirplane;
    private javax.swing.JComboBox ComboBoxFrom;
    private javax.swing.JComboBox ComboBoxTo;
    private com.toedter.calendar.JDateChooser arrivalTime;
    private com.toedter.calendar.JDateChooser departureTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(IDataManagement dm) {
        IAirportAccess aa = BAirportAccess.build();
        IAirplaneManagement am = BAirplaneManagement.build(manegerRole);
        ComboBoxFrom.removeAllItems();
        ComboBoxTo.removeAllItems();
        ComboBoxAirplane.removeAllItems();
        
        Iterator<IAirport> itr = aa.all(r);
        
        IAirport airport;
        while(itr.hasNext()){
            airport = itr.next();
            ComboBoxFrom.addItem(airport);
            ComboBoxTo.addItem(airport);
        }
        Iterator<IAirplane> itrAp = am.all();
        IAirplane airplane;
        while(itrAp.hasNext()){
            airplane = itrAp.next();
            ComboBoxAirplane.addItem(airplane);
        }
        
        ComboBoxFrom.revalidate();
        ComboBoxTo.revalidate();
        ComboBoxAirplane.revalidate();
    }

    @Override
    public void init(IRole r) {
        this.r = r;
    }
}
