/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import AplicationObject.IFlight;
import DataAccess.IDataManagement;
import DataAccess.IObserver;
import GettingFlightsAtCompany.BFlightsAtCompany;
import GettingFlightsAtCompany.IFlightsAtCompany;
import java.util.Iterator;
import javax.swing.JPanel;
import logon.BAuthentication;
import logon.IRole;

/**
 *
 * @author Evgeniy
 */
public class ViewAllFlights extends JPanel implements IView, IObserver{

    IRole r = BAuthentication.getRole();

    IFlightsAtCompany fatc;
    /**
     * Creates new form ViewFlights
     */
    public ViewAllFlights() {
        initComponents();
        fatc = BFlightsAtCompany.build(r);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FligthsPane = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout(5, 5));

        jScrollPane1.setViewportView(FligthsPane);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane FligthsPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(IDataManagement dm)
    {
        Iterator<IFlight> itr;
        itr = fatc.all();

        int i = 1;

        StringBuilder sb=new StringBuilder();
        sb.append("Рейсы компании: \n");
        while(itr.hasNext())
        {
            IFlight fl = itr.next();
            sb.append(i + ". (" + fl.flightsID() + ")"
                    + " из " + fl.startAirport().toString()
                    + " в "  + fl.finishAirport().toString()
                    + "("+fl.arrivalTime().toString()+":"
                    + fl.departureTime() + ") \n"
            );
            i++;
        }
        System.out.println();
        FligthsPane.setText(sb.toString());
    }

    @Override
    public void init(IRole r) {
        this.r = r;
    }
}
